nginx:
  image: umputun/nginx-le:latest
  restart: unless-stopped
  logging:
    driver: json-file
    options:
      max-size: "10m"
      max-file: "5"
  volumes:
    - ./ssl:/etc/nginx/ssl
    - ./index.html:/srv/docroot/project2/index.html
  ports:
    - 80:80
    - 443:443
  environment:
    - TZ=Europe/Moscow
    - LETSENCRYPT=true
    - LE_EMAIL=tech-support@nevatrip.ru
    - LE_FQDN=project2.nevatrip.ru
  tty: true
  networks:
    - project2-network

networks:
  project2-network:
    driver: bridge
