nginx:
  image: umputun/nginx-le:latest
  restart: unless-stopped
  logging:
    driver: json-file
    options:
      max-size: "10m"
      max-file: "5"
  ports:
    - 80:80
    - 443:443
  environment:
    - TZ=Europe/Moscow
  tty: true